# Общие поля для примера Сюда вписывать примитивы 
common:
  # Интовое поле Записывается сюда какое-то значение целочисленное (int)
  int_field: 220
  # Флаг значение Тут понятно должно быть что оно в себе хранит (bool)
  flag: false
  # Строчный тип типа Используется для хранения строки (str)
  string: STR
  # Тут хранится enum (MyEnum)
  enum_field: value2
  # Списочек (int)
  list_field:
  - 1
  - 2
  - 3
  - 4
  # Пустой списочек (int)
  empty_list: []
  # Кортеж (bool)
  tuple_field:
  - false
  - true
  - true
  # Пустой кортеж (bool)
  empty_tuple: []
# lvl1 
lvl1:
  # lvl2 
  lvl2:
    # lvl3 
    lvl3:
      # lvl4 
      lvl4:
        # lvl5 
        lvl5:
          # lvl6 
          lvl6:
            # Нажми на меня (str)
            click_me: https://www.youtube.com/watch?v=dQw4w9WgXcQ
# Абсолютно разношерстные поля 
more_fields:
  empty: 0
  # Some label (int)
  label: 1
  # Some hint (int)
  hint: 2
  # 0-30 (int)
  rule_range: 4
  # min 5 (int)
  rule_min: 10
  # max 15 (int)
  rule_max: 5
  # Email адрес (str)
  email: some_email@gmail.com
  default: 4400
  port: 3000
# Данные для подключения к серверу 
server_field:
  # Адрес сервера (str)
  host: 0.0.0.0
  # Порт сервера (int)
  port: 0
  # Протокол подключения HTTP/HTTPS (HTTPVariant)
  protocol: https
  # Логин пользователя (str)
  user: ''
  # Пароль пользователя (str)
  password: ''
# Время создания конфига (str)
created_time: '2023-12-21T13:34:41.489553'
# Кастомное дефолт значение 1 
custom_default:
  # Тут должно было быть 1234 (int)
  default_1234: 1111
# Кастомное дефолт значение 2 
custom_default_2:
  # Тут должно было быть 1234 (int)
  default_1234: 2222
